// Comentarios genéricos para posts
const BLOG_COMMENTS = [
  "🔥🔥 RaveHub lo hace de nuevo! 🔥🔥",
  "¡Puro fuego! RaveHub está en todo 🔥🎶",
  "¿Cuándo el siguiente evento, RaveHub? 🔥🔥",
  "Tio RaveHub, ¡esto está brutal! 🤘🔥",
  "No puedo esperar para el próximo festival 😎🎧",
  "¡Esto está épico! 🎉 #RaveHub 💥",
  "RaveHub siempre sabe cómo sorprendernos 🔥💃",
  "🔥🔥 RaveHub siempre en el top 🔥🔥",
  "¡Increíble evento! RaveHub siempre nos tiene lo mejor 🔥🎶",
  "Somos RaveHub 🔥, ¡Siempre con el mejor contenido! 💥",
  "¡Eso es lo que me gusta! #RaveHub 🎶💣",
  "Vamos con todo, ¡RaveHub lo rompe! 🔥💥",
  "¡Saludos, RaveHub! 👊🔥 Esto se viene con todo",
  "¡Esto está brutal! No puedo esperar el próximo festival 🎧🔥",
  "La energía de RaveHub siempre está por las nubes 🚀🔥",
  "🔥🔥 Esto está que arde, RaveHub lo sabe 🔥🔥",
  "¡Qué locura! 🤯🔥 No me lo puedo perder #RaveHub",
  "¡Puro amor por la música electrónica! 🎶🔥",
  "Súper hype por todo lo que está por venir 👀🔥",
  "RaveHub me tiene enganchado con todo 🔥🤘",
  "¡Increíble! No puedo esperar más 😍🔥",
  "Esto se ve demasiado épico 🔥 RaveHub siempre la rompe",
  "No hay nadie como RaveHub 🔥🎧",
  "¡Qué bien está quedando esto! 🔥🔥",
  "Este es el contenido que esperaba, RaveHub🔥💥",
  "¡Dame más! #RaveHub siempre sabe lo que necesitamos 🤩",
  "Esa vibe de RaveHub me encanta, ¡la mejor! 🔥",
  "¡Vamos con todo! 💥🔥 RaveHub es lo máximo",
  "¡Esto está a otro nivel! RaveHub se la jugó 🔥💣",
  "Tio RaveHub, ¿cuando más eventos? 🔥🎉",
  "¡La energía de RaveHub está on fire! 🔥🔥",
  "¡Gracias por el contenido, RaveHub! 🔥🔊",
  "Siempre con la mejor música, gracias RaveHub 🎧🔥",
  "RaveHub siempre dando lo mejor 💥🔥",
  "¡Puro fuego, RaveHub! 🔥🔥",
  "¡Qué locura! 😍🔥 Vamos con todo RaveHub",
  "Esto se ve muy bueno, ¡amo el contenido de RaveHub! 🔥",
  "¡Esto está brutal! RaveHub siempre sorprende 🔥💥",
  "Increíble todo lo que estás haciendo RaveHub 🔥🎧",
  "¡Vamos con todo RaveHub! No me lo quiero perder 🔥🔥",
  "🔥🔥 Siempre RaveHub🔥🔥",
  "RaveHub sabe cómo ponernos en el mood 🔥🎶",
  "¡Sí, sí! Me encanta todo lo que hace RaveHub 🔥🎧",
  "🔥🔥 Este evento va a estar de locos 💥🔥",
  "Siempre con la mejor energía, RaveHub 🔥💣",
  "¡Estamos listos para lo que sea, RaveHub! 🔥🎧",
  "¡Puro fuego, siempre con RaveHub! 🔥🔥",
  "RaveHub siempre está a otro nivel 🔥💥",
  "¡Estamos en fuego, RaveHub! 🔥🔥",
  "¿Quién más está hypeado con RaveHub? 🔥🎶",
  "RaveHub hace magia 🔥🎶💥",
  "¡Esto está tremendo! 🔥🔥 Vamos con todo RaveHub",
  "¡Gracias por tanto RaveHub! 🔥🔥",
  "¡Más energía que nunca con RaveHub! 🔥💣",
  "Siempre en la cima, RaveHub 🔥🎧",
  "Tio RaveHub 🔥🔥 ¡Esto está épico!",
  "¡Quiero más RaveHub! 🔥🎶",
  "RaveHub lo hace de nuevo 🔥🔥",
  "¡Esto es lo que más me gusta de RaveHub! 🎧🔥",
  "Increíble lo que están haciendo, RaveHub 🔥💥",
  "Esto va a estar brutal, RaveHub 💣🔥",
  "¡Este contenido es oro, RaveHub! 🔥🎶",
  "Ya quiero el próximo evento 🔥🔥 #RaveHub",
  "¡A seguir bailando con RaveHub! 🔥💃",
  "¡Dame más de esto, RaveHub! 🔥🎧",
  "RaveHub, el rey de los festivales 🔥💥",
  "🔥🔥 Este año va a ser épico, RaveHub lo sabe",
  "🔥🔥 Puro fuego con RaveHub",
  "Estamos en fuego con RaveHub 🔥🔥",
  "Gracias por el contenido, RaveHub 🔥🎧",
  "Vamos con todo, RaveHub! 🔥🔥",
  "¡Esto está a otro nivel! 🔥🔥 RaveHub siempre sorprende",
  "🔥🔥 ¡Ya estoy listo para la fiesta con RaveHub! 🔥🔥",
  "¡Impresionante! 🔥🔥 RaveHub siempre al top",
  "¡No me lo puedo perder! 🔥🔥 Gracias RaveHub",
  "🔥🔥🔥 Este va a ser el mejor evento 🔥🔥🔥",
  "¡Dale, RaveHub! 🔥🔥 Siempre a lo grande",
  "¡Con todo RaveHub! 🔥🔥🎶",
  "Me encanta el contenido, RaveHub 🔥💣",
  "RaveHub siempre dando lo mejor 🔥💥",
  "¡Eso está brutal! RaveHub🔥",
  "¡Vamos con todo! #RaveHub 🔥🔥",
  "🔥🔥🔥 Estamos on fire con RaveHub 🔥🔥🔥",
  "RaveHub siempre sorprendiendo 🔥🔥",
  "Esto se viene con todo 🔥🔥 ¡Gracias RaveHub!",
  "¡Esto es pura magia! 🔥🔥 #RaveHub",
  "¡Estamos listos para el festival! 🔥🔥🎶",
  "¡Puro fuego, RaveHub! 🔥🎧",
  "¡La mejor energía siempre con RaveHub! 🔥🔥",
  "¡RaveHub siempre está un paso adelante! 🔥🔥",
  "¡Fuego! 🔥🔥 Vamos con todo RaveHub",
  "¡RaveHub lo hace de nuevo! 🔥🔥🎶",
  "¡Esto está épico, RaveHub! 🔥🔥💥",
  "🔥🔥 ¡La fiesta está asegurada con RaveHub! 🔥🔥",
  "¡Puro fuego, RaveHub! 🔥🔥",
  "RaveHub nos tiene a todos hypeados 🔥🔥",
  "¡Qué energía! RaveHub siempre la rompe 🔥🔥",
  "No hay nada como los eventos de RaveHub 🔥🔥",
  "RaveHub siempre sabe lo que queremos 🔥🔥",
  "¡Vamo' con todo RaveHub! 🔥🔥🔥",
  "¡Eso es todo RaveHub! 🔥🔥 Vamos a romperla",
  "🔥🔥 ¡Vamo' con todo RaveHub! 🔥🔥",
  "Esto va a ser una locura 🔥🔥 Vamos RaveHub",
  "¡Puro fuego! 🔥🔥 RaveHub nos trae lo mejor",
  "¡Estoy listo para el festival! 🔥🔥",
  "¡Esto está🔥🔥🔥, no me lo pierdo por nada",
  "¡Puro fuego, RaveHub! 🔥🔥🎶",
  "¡La mejor energía con RaveHub! 🔥🔥",
  "¡Estamos prendidos con RaveHub! 🔥🔥🔥",
  "¡Qué locura, RaveHub! 🎧🔥",
  "¡Dale, RaveHub! 💥👊",
  "Esto va a ser épico 🤩🔥",
  "No puedo esperar para el próximo evento 👀🎶",
  "¡Vamos con todo, RaveHub! 🕺💥",
  "Esto está increíble, ¡RaveHub lo hizo de nuevo! 💥🔥",
  "🔥 ¡Qué energía! 🎶💣",
  "Vamos a romperla con RaveHub 🔥💃",
  "Me encanta este vibe, RaveHub! 🎧💥",
  "¡Con todo, RaveHub! 🔥🎶",
  "¡Eso está brutal! 🔥🔥🙌",
  "RaveHub siempre tiene la mejor energía ✨🔥",
  "¡RaveHub nos tiene a todos hypeados! 🔥💃",
  "¡Esto es fuego puro! 🔥💥",
  "¡Siempre con lo mejor! 🔥🎧 RaveHub",
  "¡Estoy listo para el festival, RaveHub! 🔥💣",
  "RaveHub está rompiendo 🔥💥",
  "¡Esos beats están 🔥🔥 RaveHub, siempre lo mejor!",
  "¡Esto está quedando de locos! 🔥🎧",
  "¡Vamos con todo, RaveHub! 🎉💥",
  "¡Puro fuego! 🔥🔥 #RaveHub",
  "¡Lo que se viene con RaveHub está increíble! 🔥🎧",
  "RaveHub siempre sorprendiendo, ¡qué bien! 🔥💥",
  "¡No hay nadie como RaveHub! 🔥💣",
  "¡Esto está fuera de control! 🔥🎶",
  "Vamos a romperla, RaveHub 🔥🔥",
  "🔥🔥 Vamo' con todo RaveHub 🎶",
  "¡Súper hypeado para el próximo evento! 🎉🔥",
  "RaveHub siempre tiene la mejor música 🎶🔥",
  "¡Esto está muy bueno! 🔥🎧",
  "¡La fiesta se viene con todo, RaveHub! 🎉🔥",
  "🔥🔥 ¡Esto está tremendo! 🔥💥",
  "RaveHub siempre trae la mejor energía 💥🎶",
  "¡Dame más! 🔥🔥 RaveHub",
  "¡Vamos con todo, RaveHub! 💥🎶",
  "¡Eso está épico, RaveHub! 🔥🔥",
  "¡Qué bien lo está haciendo RaveHub! 🔥🎧",
  "¡Puro fuego en la pista! 🔥🔥",
  "Esto va a estar brutal, RaveHub 💥🔥",
  "¡Puro fuego! 🔥💣 RaveHub nos tiene hypeados",
  "¡RaveHub siempre con la mejor onda! 🔥🎧",
  "¡Vamo' con todo! 💥🔥 RaveHub lo sabe",
  "¿Quién más está listo para el festival? 🎉🔥",
  "¡Este contenido está 🔥🔥! RaveHub siempre la rompe",
  "¡RaveHub lo hace de nuevo! 💥🔥",
  "Puro fuego con RaveHub 🔥🎶",
  "¡RaveHub tiene la mejor música siempre! 🔥🎧",
  "🔥🔥 Este evento va a ser épico 🎉🔥",
  "¡La energía está por las nubes! 🔥🔥",
  "¡Increíble! RaveHub siempre sorprende 🎶💥",
  "¡Me muero por el próximo evento! 🔥💣",
  "¡RaveHub está encendido! 🔥🔥",
  "Esto es lo que más me gusta, ¡vamos RaveHub! 🔥💥",
  "¡Nos vemos en el próximo evento! 🔥🎧",
  "¡Eso está a otro nivel, RaveHub! 🔥🔥",
  "Vamos con todo 🔥💣 RaveHub lo sabe",
  "¡No puedo esperar para la próxima fiesta! 🔥🎶",
  "Siempre con la mejor música 🔥🎧 RaveHub",
  "¡Esto va a estar de locos! 🔥🔥",
  "RaveHub lo está rompiendo, ¡qué bien! 🔥💥",
  "¡Dale, RaveHub! 💥🔥 Siempre dando lo mejor",
  "¡Qué locura lo de RaveHub! 🔥🎶",
  "¡Súper hypeado! 🔥💥 Vamos con todo RaveHub",
  "¡Siempre con la mejor música, RaveHub! 🎧🔥",
  "¡Esto está que arde! 🔥🎶",
  "🔥🔥 Esto va a ser un fiestón 💥🎶",
  "RaveHub siempre nos tiene lo mejor 🔥💣",
  "🔥🔥 Esto está brutal, RaveHub siempre sorprende",
  "¡No puedo esperar más, RaveHub! 🔥🎧",
  "🔥🔥 RaveHub lo está petando siempre",
  "¡Qué buena vibra, RaveHub! 🔥🎶",
  "¡Esto es lo que más me gusta de RaveHub! 🔥🔥",
  "¡RaveHub siempre nos tiene hypeados! 🎧🔥",
  "¡Puro fuego, RaveHub! 🔥🎶",
  "🔥🔥 ¡Qué buena energía! 🎶🔥",
  "Siempre rompiéndola, RaveHub 🔥🎧",
  "¡Vamo' con todo! 💥🔥 RaveHub nos sorprende siempre",
  "RaveHub siempre está a otro nivel 🔥🎧",
  "🔥🔥 ¡Esto es lo que esperaba de RaveHub! 🎶💥",
  "¡Dale, RaveHub! 🔥💣 Esto se viene con todo",
  "¡Qué bien lo está haciendo RaveHub! 🔥🔥",
  "¡Esto está increíble! 🔥💥 RaveHub siempre sorprende",
  "¡RaveHub está rompiendo! 🔥🎶",
  "🔥🔥 Vamos con todo, RaveHub lo hace de nuevo",
  "¡Impresionante todo lo que está haciendo RaveHub! 🔥🔥",
  "¡Puro fuego con RaveHub! 🔥🎶",
  "¡Esto está fuera de control! 🔥🔥🎧",
  "¡RaveHub lo sabe! 🔥💥",
  "¡Gracias RaveHub! 🔥🔥",
  "¡Eso está 🔥🔥! Vamos con todo, RaveHub",
  "RaveHub siempre está a tope 🔥🔥",
  "¡Vamos a romperla con RaveHub! 🔥🎶",
  "¡Esto está brutal, RaveHub! 🔥💥",
  "¡No hay nadie como RaveHub! 🔥🎧",
  "🔥🔥 ¡Esto va a ser épico! 🎶💥",
  "¡Gracias RaveHub por siempre traernos lo mejor! 🔥🔥",
  "¡Esto está on fire, RaveHub! 🔥🎶",
  "🔥🔥 ¡No me lo puedo perder! RaveHub lo tiene todo",
  "Vamos con todo, RaveHub! 🔥🎶💥",
  "¡Esto está tremendo! 🔥🎧 RaveHub",
  "¡Qué buena vibra, RaveHub! 🔥🔥🎧",
  "¡Puro fuego, RaveHub! 🔥💥",
  "¡Este evento está brutal! 🔥🎶",
  "¡Esto está increíble! 🔥🎶 RaveHub siempre lo mejor",
  "🔥🔥 Vamos RaveHub, ¡no hay quien nos pare! 🔥🔥",
  "¡Esto se viene con todo! 🔥🎧",
  "¡La mejor música siempre con RaveHub! 🎶🔥",
  "¡Qué locura, RaveHub! 🔥🔥",
  "¡Puro fuego! 🔥🔥 RaveHub siempre nos sorprende",
  "🔥🔥 Puro fuego con RaveHub",
  "¡RaveHub es lo máximo! 🔥🔥🎧",
  "🔥🎧🎶",
  "✨💥🔥",
  "🎉🎧💥",
  "🔥🎶🔥",
  "🎶🔥🔥🔥",
  "💥🎧🔥",
  "💥🎉🎶",
  "🔥🎧💥",
  "🎧💥🎶",
  "🎧🎉💥🔥",
  "🔥🔥🎶🎧",
  "🎶💥💥",
  "🎉🔥🎶",
  "🎧🔥🎶🔥",
  "💥🎶🎧",
  "🔥🔥🎉🎶",
  "💥🎧🎶🎉",
  "🎶🔥🎧",
  "✨🎧🔥🎶",
  "🎶🔥💥",
  "💥🎉🔥🎶",
  "🔥🔥💥🎧",
  "🎧🎶🔥🔥",
  "🎶🎉🎶💥",
  "🎉🔥🎧🔥",
  "🎧💥🎶🔥",
  "💥🎧🎶🔥",
  "🎉🎶🔥💥",
  "💥🎶🔥🎧",
  "🔥💥🎶🎧",
  "🎶🎧🔥💥",
  "🔥🎧🎶🎉",
  "💥🎶💥🎧",
  "🎧🎶🔥🎧",
  "🎶🎧💥🔥",
  "💥🎶🎧💥",
  "🔥🎧💥🎶",
  "🎶🎧🔥💥",
  "🎧🔥💥🎶",
  "🎧🎉🎶🔥",
  "🔥💥🎶🎉",
  "🎶🔥🎧💥",
  "💥🔥🎧🎶",
  "🎧🎶💥🔥",
  "🎉🔥🎧💥",
  "🎶🎉🔥💥",
  "🎶🎧💥🔥",
  "🎉💥🔥🎶",
  "💥🎧🎶🎉",
  "🎶💥🎧🎉",
  "🔥🎶🎧💥",
  "💥🔥🎧🎉",
  "🔥🎧💥🎉",
  "🎧💥🎉🎶",
  "💥🎧🔥🎶",
  "🎧🎶🎧🔥",
  "🎉🎶🔥💥",
  "💥🎧🔥🎶",
  "🎶💥🔥🎉",
  "🔥🎧💥🎉",
  "🎉🎧🔥🎶",
  "💥🎶🎧🔥",
  "🎧🎉💥🔥",
  "🎶🔥🎉🎧",
  "🔥🎶🎧💥",
  "🎧🎶🎉💥",
  "🔥💥🎉🎧",
  "🎶🎧💥💥",
  "🔥💥🎶🎧",
  "🎉🎶💥🎧",
  "🎧🎶🔥💥",
  "🎶💥🎧🎉",
  "💥🎧🔥🎧",
  "🔥🎧🎶🎶",
  "💥🎶🔥🎉",
  "🎶💥🎧🔥",
  "🎧💥🎶🎉",
  "💥🎶🎧🔥",
  "🎧🎶🔥🔥",
  "🎉💥🎶🎧",
  "💥🎶🎉🎧",
  "🔥💥🎶🎧",
  "🎶🎧🔥🎧",
  "🎧💥🎶🔥",
  "🎉🎧🔥💥",
  "💥🎧🎶🎉",
  "🔥🎧🎶🎶",
  "🎧🎶💥🎉",
  "🎶🔥🎉🎧",
  "🎧🔥💥🎶",
  "💥🎧🎧🎶",
  "🔥🎉🎶💥",
  "🎶💥🎧🔥",
  "🎧💥🎶🎶",
  "💥🎧🎶🎶",
  "🎧🎶💥💥",
  "🎶💥🎧💥",
  "🎉🔥🎶🎧",
  "🎧🎉🎶🔥",
  "🎧🎶🎉🎶",
  "🔥💥🎧🎧",
  "🎶💥🔥🎧",
  "💥🎧🔥🎶",
  "🔥🎶🎧🎉",
  "🎧💥🔥🎶",
  "🎉🔥🎧💥",
  "🎶🎧💥🎧",
  "🎧🎉🎧🔥",
  "🎉🎶💥🎧",
  "🎶🔥🎧💥",
  "💥🎧🎶🎧",
  "🎧🎶🎉🔥",
  "🎧🎶💥💥",
  "🎧🎶💥🎧",
  "🎧🔥🎶💥",
  "🔥🎉🎶💥",
  "🎧🎶💥🎉",
  "🎶🎧🔥🎶",
  "🎧💥🎶💥",
  "🎧🎶🔥🎧",
  "🎧🎶🔥💥",
  "🔥💥🎧🎧",
  "🎧🎶🎧💥",
  "🎶💥🎧🎶",
  "🎉🔥🎶🔥",
  "🎧🎶🎉💥",
  "🎶💥🎧🔥",
  "🎉🔥🎶💥",
  "🔥 ¡Esto es lo que necesitamos! 💥🎶",
  "🎉 Que buena vibra, ¡lo amé! 🎶💥",
  "💥💫 Siempre subiendo el nivel 🔥🎧",
  "🌟 Esto está increíble, no puedo esperar a más 🔥",
  "🎶 ¡Energía total! 🚀🔥",
  "🔥💥 Este contenido está ON FIRE 🎧🎶",
  "🎉💥 ¡Dándolo todo! 😎🎶",
  "🔥 ¡Esto sí que está épico! 🎧💥",
  "💥🌈 ¡El mejor post de todos! 🎶🔥",
  "🎧🎶 ¡Nos vamos de festival! 🔥💫",
  "💥 Esto es lo que me gusta ver 🎉🔥",
  "🔥🎶 El mejor contenido, sin duda 🔥💥",
  "🎧🎉 Esto está de lujo, ¡qué energía! 💥",
  "🔥🎶 Más de esto 💥🎉",
  "🎉🔥 Este post está lleno de fuego 🎧💥",
  "🔥🎶 Sin palabras 💥🎧",
  "🎧💥 Lo estoy compartiendo ya 🎉🎶",
  "🔥🎉 Vibes de festival por todos lados 🎶🔥",
  "🎶 Esto es un vibe increíble 🔥💥",
  "🎧💥 A todo volumen 🔥🎉",
  "🎶 Esto es lo máximo 🔥💥",
  "🎧🔥 Qué fire 🎶💥",
  "💥🎶 Esto sí es puro fuego 🎉🔥",
  "🔥🎧 Vamos con todo 🎶💥",
  "🎉 Este contenido es puro fuego 🎧💥",
  "🔥🎧 Eso está brutal 🎶💥",
  "🎶💥 De fiesta siempre 🔥🎧",
  "🔥💥 Esto es lo mejor que he visto hoy 🎶",
  "🎧🔥 Esto me hizo el día 🎉💥",
  "🎶🔥 Este es el tipo de post que quiero ver 🎧💥",
  "💥🎶 Esto se merece un like 🎉🔥",
  "🎧🎉 Esto está épico 💥🎶",
  "🔥🎧 Esto sí que lo esperaba 🎶💥",
  "🎶 A todo volumen y a disfrutar 🔥🎉",
  "🔥🎶 Siempre rompiendo con lo mejor 💥🎧",
  "🎧🔥 Qué buena vibra 🎶💥",
  "🔥🎶 Esto me tiene atrapado 🎧💥",
  "💥🎶 Qué buena energía 🎉🎧",
  "🎶🔥 Esos son los vibes que necesitamos 💥🎧",
  "🔥🎉 Puro fuego, siempre 🎧🎶",
  "🎧🎶 Lo mejor está por venir 🔥💥",
  "🎶💥 Un fuego que no para 🎧🎉",
  "🎧💥 Esto lo grito al mundo 🔥🎶",
  "💥🎶 Esto sí que está en otro nivel 🎉🔥",
  "🎧🎶 Esto me lleva directo a la pista 💥🔥",
  "🔥🎧 Esto es lo que quiero ver 🎶🔥",
  "🎉🎶 Sin parar de bailar 💥🔥",
  "🔥💥 Vamos con todo 🎶🎧",
  "🎶🔥 Esto es música para mis oídos 💥🎧",
  "💥🎶 Increíble! Lo quiero en repeat 🔥🎧",
  "🎧🔥 Esto es lo mejor 🎶💥",
  "🎶💥 Pura energía positiva 🔥🎧",
  "🔥🎉 Esto está increíble, chicos 🎧🎶",
  "🎶🎧 Me hizo el día 💥🔥",
  "🔥🎧 Esto es festival puro 🎶💥",
  "🎶💥 Vamos a romperla 🔥🎧",
  "🎧💥 Este contenido es oro 🔥🎶",
  "💥🎶 Esto está brutal, chicos 🔥🎧",
  "🎧🔥 Qué épico 🎶💥",
  "🎶🔥 Así me gustan los posts 💥🎧",
  "🔥🎉 Qué fiesta 🎶💥",
  "🎧💥 Qué ganas de ir a un festival 🎶🔥",
  "🎶🔥 Esto sí que es lo que quiero ver 🎧💥",
  "🔥🎧 Esto sí que me hizo vibrar 🎶💥",
  "��💥 Esto es magia 🎶🎧",
  "🔥🎶 Esto es lo que más me gusta 🎧💥",
  "💥🎧 Vibes de festival todo el día 🎶🔥",
  "🎧🔥 Esto está de otro planeta 💥🎶",
  "🔥🎶 Quiero más de esto 🎧💥",
  "🎶🎧 Espectacular 💥🔥",
  "🔥🎧 Imparable 🎶💥",
  "🎶🔥 Vamos a reventar 🎧💥",
  "🎉🎶 Esto es pura energía 🔥🎧",
  "💥🔥 Esto está épico, chicos 🎶🎧",
  "🎧💥 Esto me hizo saltar de la emoción 🎶🔥",
  "🔥🎶 Qué ganas de más 🎧💥",
  "🎶🔥 Esto es lo que me gusta ver 🎧💥",
  "🎧🔥 Esto está fuera de serie 🎶💥",
  "💥🎧 Puro fuego 🎶🎧",
  "🎧🎶 Lo mejor 💥🔥",
  "🎶💥 Esto lo quiero en repeat 🎧🔥",
  "Increíble noche 🔥🔥🔥",
  "No siento las piernas, pero valió la pena 💣",
  "Esto fue épico 😍🙌",
  "La energía fue única 🔥🔥",
  "Nos vemos el próximo año 🔥🙌",
  "¡Qué noche tan inolvidable! 😍🔥",
  "La música estuvo de otro nivel 🔊",
  "Lo mejor de lo mejor, ¡gracias por todo! 🔥",
  "¡Volveré el próximo año! 🙌🔥",
  "El evento fue increíble, no lo olvidaré ❤️🔥",
  "¡Qué show tan brutal! 🔥🔥",
  "Esto fue todo lo que esperábamos y más 🔥🔥🔥",
  "Este fue un evento épico, ¡gracias por tanto! 🙌🎶",
  "Sin palabras, increíble todo 🔥🙌",
  "Ya quiero que sea el próximo evento 🔥",
  "¡Qué gran fiesta! 🔥❤️",
  "La música nos dejó sin aliento 😱🔥",
  "¡Gracias por esta experiencia única! ❤️🔥",
  "La mejor noche de mi vida, ¡no puedo esperar para la próxima edición! 🔥🔥🔥",
  "¡Nos vemos en la siguiente edición! 🔥🙌",
  "Ya estoy contando los días para el próximo evento 😎🔥",
  "Increíble la producción, todo estuvo perfecto 🔥",
  "¡Lo mejor del año! 🙌🔥",
  "¡Que siga la fiesta! 🔥🔥🔥",
  "Esto es lo que llamo una verdadera fiesta 🔥🔥🔥",
  "¡Nos vemos en el próximo evento! 🔥🙌",
]

// Reseñas para posts
const BLOG_RATINGS = [
  "Este artículo me pareció muy completo y bien investigado. La información es clara y fácil de entender.",
  "Me gustó mucho la forma en que se aborda el tema, con ejemplos prácticos y consejos útiles.",
  "Excelente contenido, muy relevante para la actualidad. Definitivamente lo recomendaré.",
  "El autor demuestra un gran conocimiento sobre el tema. Me ha ayudado a entender conceptos que antes no comprendía.",
  "Artículo muy bien estructurado y con información valiosa. Lo guardaré como referencia.",
  "Me encantó la profundidad con la que se trata el tema. Muy profesional y educativo.",
  "Contenido de alta calidad, se nota la investigación detrás. Felicitaciones al autor.",
  "Este post resolvió muchas de mis dudas. Gracias por compartir tu conocimiento.",
  "Uno de los mejores artículos que he leído sobre este tema. Claro, conciso y muy informativo.",
  "La información presentada es muy útil y está respaldada por buenas fuentes. Excelente trabajo.",
]

// Reseñas para productos escritas por mujeres
const PRODUCT_REVIEWS_FEMALE = {
  polo: [
    "Me encantó este polo, el material es muy suave y la talla es perfecta.",
    "El polo es precioso, me quedé fascinada con el diseño y los colores.",
    "Compré este polo para mi hermano y le quedó genial, estoy muy contenta con la compra.",
    "La calidad del polo es excelente, lo he lavado varias veces y sigue como nuevo.",
    "Estoy encantada con este polo, el corte es muy favorecedor y el material transpirable.",
    "Me quedé sorprendida con lo bien que me queda este polo, definitivamente compraré más.",
    "El polo llegó en perfectas condiciones y es exactamente como se ve en las fotos.",
    "Súper cómodo este polo, perfecto para el día a día y para eventos casuales.",
    "La tela del polo es de muy buena calidad, estoy muy satisfecha con mi compra.",
    "Me encanta cómo combina este polo con todo mi guardarropa, fue una excelente elección.",
  ],
  casaca: [
    "Esta casaca es perfecta para el invierno, muy abrigadora y con un diseño precioso.",
    "Me encantó la casaca, el material es de excelente calidad y me queda perfecta.",
    "Compré esta casaca para mi viaje y no podría estar más feliz, es ligera pero abrigadora.",
    "La casaca es hermosa, la talla y color corresponden exactamente a lo que esperaba.",
    "Estoy fascinada con esta casaca, tiene muchos bolsillos y es muy funcional.",
    "La casaca llegó antes de lo esperado y es incluso mejor de lo que se ve en las fotos.",
    "Me quedé maravillada con los detalles de esta casaca, se nota que está bien confeccionada.",
    "Esta casaca es una excelente inversión, muy versátil y de buena calidad.",
    "Compré esta casaca para mi hija y le encantó, dice que es muy cómoda y abrigadora.",
    "La casaca es preciosa y muy cálida, perfecta para las noches frías.",
  ],
  gorra: [
    "Esta gorra es perfecta, se ajusta muy bien y el diseño es precioso.",
    "Me encantó la gorra, el material es de buena calidad y el color es exactamente como en la foto.",
    "Compré esta gorra para mi novio y le quedó genial, estoy muy contenta con la compra.",
    "La gorra es muy bonita y de buena calidad, estoy muy satisfecha con mi compra.",
    "Estoy encantada con esta gorra, es ajustable y muy cómoda de llevar todo el día.",
    "La gorra llegó en perfectas condiciones y es exactamente como se ve en las fotos.",
    "Me quedé sorprendida con la calidad de esta gorra, definitivamente compraré más de esta marca.",
    "La gorra es perfecta para el verano, me protege bien del sol y es muy estilosa.",
    "Estoy muy contenta con esta gorra, combina con todo y es muy práctica.",
    "La gorra tiene un diseño único que me encanta, recibí muchos cumplidos cuando la usé.",
  ],
  pantalon: [
    "Este pantalón es perfecto, la tela es de muy buena calidad y el corte es muy favorecedor.",
    "Me encantó este pantalón, se ajusta perfectamente a mi figura y es muy cómodo.",
    "Compré este pantalón para el trabajo y es justo lo que necesitaba, elegante y cómodo.",
    "El pantalón es precioso, la talla corresponde perfectamente y el color es hermoso.",
    "Estoy fascinada con este pantalón, tiene un corte muy moderno y la tela es resistente.",
    "El pantalón llegó rápido y en perfectas condiciones, me queda como un guante.",
    "Me quedé maravillada con lo bien que me queda este pantalón, muy contenta con mi compra.",
    "Este pantalón es una excelente adición a mi guardarropa, versátil y de buena calidad.",
    "La tela del pantalón es suave pero resistente, estoy muy satisfecha con la compra.",
    "Me encanta cómo se ve este pantalón, el diseño es muy favorecedor para cualquier tipo de cuerpo.",
  ],
  zapatilla: [
    "Estas zapatillas son perfectas, muy cómodas desde el primer uso y con un diseño precioso.",
    "Me encantaron estas zapatillas, el material es de excelente calidad y son muy ligeras.",
    "Compré estas zapatillas para hacer ejercicio y son justo lo que necesitaba, muy cómodas.",
    "Las zapatillas son hermosas, la talla corresponde perfectamente y el color es exacto.",
    "Estoy fascinada con estas zapatillas, tienen buen soporte y son muy estilosas.",
    "Las zapatillas llegaron antes de lo esperado y son incluso más bonitas en persona.",
    "Me quedé maravillada con la comodidad de estas zapatillas, perfectas para largas caminatas.",
    "Estas zapatillas son una excelente inversión, muy versátiles y de buena calidad.",
    "La suela de las zapatillas tiene muy buen agarre, estoy muy satisfecha con la compra.",
    "Me encantan estas zapatillas, son tan cómodas que las uso todos los días.",
  ],
  accesorio: [
    "Este accesorio es perfecto, complementa muy bien mis outfits y es de buena calidad.",
    "Me encantó este accesorio, el diseño es muy original y la calidad es excelente.",
    "Compré este accesorio para un regalo y fue un éxito total, muy bonito y bien acabado.",
    "El accesorio es precioso, exactamente como se ve en las fotos y de buena calidad.",
    "Estoy fascinada con este accesorio, es muy versátil y combina con todo.",
    "El accesorio llegó en un empaque muy bonito, perfecto para regalo.",
    "Me quedé maravillada con los detalles de este accesorio, se nota que está bien hecho.",
    "Este accesorio es una excelente adición a mi colección, muy original y de buena calidad.",
    "La calidad del accesorio es superior a lo que esperaba, estoy muy satisfecha.",
    "Me encanta este accesorio, recibo muchos cumplidos cada vez que lo uso.",
  ],
  mochila: [
    "Esta mochila es perfecta, tiene muchos compartimentos y es muy cómoda de llevar.",
    "Me encantó esta mochila, el material es resistente al agua y el diseño es muy práctico.",
    "Compré esta mochila para la universidad y es justo lo que necesitaba, espaciosa y bonita.",
    "La mochila es preciosa, la calidad es excelente y los acabados son perfectos.",
    "Estoy fascinada con esta mochila, tiene espacio para mi laptop y todos mis accesorios.",
    "La mochila llegó en perfectas condiciones y es incluso mejor de lo que esperaba.",
    "Me quedé maravillada con la capacidad de esta mochila, muy funcional y estilosa.",
    "Esta mochila es una excelente inversión, muy duradera y con un diseño atemporal.",
    "Los tirantes de la mochila son acolchados y muy cómodos, estoy muy satisfecha.",
    "Me encanta esta mochila, es perfecta para viajes cortos y uso diario.",
  ],
  camiseta: [
    "Esta camiseta es perfecta, el material es muy suave y la talla es exacta.",
    "Me encantó esta camiseta, el diseño es muy original y la calidad es excelente.",
    "Compré esta camiseta para mi hermana y le quedó genial, está muy contenta.",
    "La camiseta es preciosa, el color es vibrante y no se deforma al lavarla.",
    "Estoy fascinada con esta camiseta, es muy cómoda y el estampado es hermoso.",
    "La camiseta llegó rápido y en perfectas condiciones, justo como se ve en la foto.",
    "Me quedé maravillada con la suavidad de esta camiseta, muy agradable al tacto.",
    "Esta camiseta es una excelente adición a mi guardarropa, versátil y de buena calidad.",
    "La tela de la camiseta es transpirable, perfecta para el verano.",
    "Me encanta esta camiseta, el corte es muy favorecedor y el diseño único.",
  ],
  sudadera: [
    "Esta sudadera es perfecta, muy abrigadora y con un diseño moderno y juvenil.",
    "Me encantó esta sudadera, el material es suave por dentro y muy cómodo.",
    "Compré esta sudadera para mi hija y le encantó, dice que es muy cómoda.",
    "La sudadera es preciosa, la talla corresponde perfectamente y el color es exacto.",
    "Estoy fascinada con esta sudadera, tiene capucha ajustable y bolsillos amplios.",
    "La sudadera llegó antes de lo esperado y es incluso más bonita en persona.",
    "Me quedé maravillada con la calidad de esta sudadera, perfecta para las tardes frescas.",
    "Esta sudadera es una excelente inversión, muy versátil y de buena calidad.",
    "El tejido de la sudadera es grueso pero no pesado, estoy muy satisfecha.",
    "Me encanta esta sudadera, es tan cómoda que la uso en casa y para salir.",
  ],
  short: [
    "Este short es perfecto, muy cómodo y con un diseño muy favorecedor.",
    "Me encantó este short, el material es de buena calidad y la talla es exacta.",
    "Compré este short para hacer ejercicio y es justo lo que necesitaba, cómodo y ligero.",
    "El short es precioso, el color es vibrante y no se deforma al lavarla.",
    "Estoy fascinada con este short, tiene bolsillos funcionales y es muy versátil.",
    "El short llegó rápido y en perfectas condiciones, justo como se ve en la foto.",
    "Me quedé maravillada con lo bien que me queda este short, muy contenta con mi compra.",
    "Este short es una excelente adición a mi guardarropa de verano, fresco y estiloso.",
    "La tela del short es ligera y transpirable, perfecta para días calurosos.",
    "Me encanta este short, el largo es perfecto y el diseño muy moderno.",
  ],
}

// Reseñas para productos escritas por hombres
const PRODUCT_REVIEWS_MALE = {
  polo: [
    "Excelente polo, la tela es de muy buena calidad y me queda perfecto.",
    "Buen polo, resistente y cómodo. Lo uso tanto para el trabajo como para salir.",
    "Este polo tiene un corte moderno que me gusta mucho, definitivamente compraré más.",
    "La calidad del polo es superior, después de varios lavados sigue como nuevo.",
    "Muy buen polo, el material es fresco y perfecto para el clima cálido.",
    "El polo llegó rápido y es exactamente como se ve en las fotos, muy satisfecho.",
    "Gran compra, el polo es versátil y combina con todo. Recomendado.",
    "Me gusta mucho este polo, el diseño es simple pero elegante.",
    "Buen producto, la relación calidad-precio es excelente.",
    "Este polo es justo lo que buscaba, cómodo para el día a día y con buen acabado.",
  ],
  casaca: [
    "Excelente casaca, muy abrigadora y con buenos acabados.",
    "Esta casaca es perfecta para el invierno, resistente al viento y muy cómoda.",
    "Muy buena compra, la casaca es ligera pero mantiene bien el calor.",
    "La calidad de la casaca es notable, los cierres funcionan perfectamente y tiene buenos bolsillos.",
    "Gran casaca, el diseño es moderno y la tela repele bien el agua.",
    "La casaca llegó antes de lo esperado y es mejor de lo que pensaba, muy contento.",
    "Compré esta casaca para un viaje y cumplió todas mis expectativas, muy recomendable.",
    "Buen producto, la casaca es versátil y se puede usar en diferentes ocasiones.",
    "Esta casaca vale cada centavo, muy duradera y con buen diseño.",
    "Me gusta mucho esta casaca, es cómoda y tiene un estilo que combina con todo.",
  ],
  gorra: [
    "Excelente gorra, se ajusta perfectamente y el material es de buena calidad.",
    "Muy buena gorra, el diseño es genial y protege bien del sol.",
    "Esta gorra es justo lo que buscaba, cómoda y con buen estilo.",
    "La calidad de la gorra es superior, después de usarla regularmente sigue en perfecto estado.",
    "Gran compra, la gorra es ajustable y queda bien con cualquier outfit.",
    "La gorra llegó en perfectas condiciones y es exactamente como se ve en las fotos.",
    "Buen producto, uso esta gorra para correr y es muy cómoda y transpirable.",
    "Esta gorra tiene un diseño único que me encanta, recibo muchos cumplidos.",
    "Muy satisfecho con esta gorra, el precio es justo por la calidad que ofrece.",
    "Me gusta mucho esta gorra, es perfecta para el día a día y para actividades al aire libre.",
  ],
  pantalon: [
    "Excelente pantalón, el corte es moderno y la tela muy cómoda.",
    "Este pantalón es perfecto para la oficina, elegante pero cómodo.",
    "Muy buen pantalón, la talla es exacta y el material de buena calidad.",
    "La calidad del pantalón es notable, después de varios lavados mantiene su forma.",
    "Gran compra, el pantalón es versátil y se puede vestir formal o casual.",
    "El pantalón llegó rápido y es exactamente como se ve en las fotos, muy satisfecho.",
    "Buen producto, uso este pantalón para el trabajo y es muy cómodo para todo el día.",
    "Este pantalón tiene un ajuste perfecto, ni muy ajustado ni muy holgado.",
    "Muy contento con este pantalón, la relación calidad-precio es excelente.",
    "Me gusta mucho este pantalón, el diseño es clásico pero con detalles modernos.",
  ],
  zapatilla: [
    "Excelentes zapatillas, muy cómodas desde el primer uso.",
    "Estas zapatillas son perfectas para correr, buen soporte y muy ligeras.",
    "Muy buenas zapatillas, el diseño es genial y son muy versátiles.",
    "La calidad de las zapatillas es superior, después de meses de uso siguen en buen estado.",
    "Gran compra, las zapatillas son cómodas para caminar todo el día.",
    "Las zapatillas llegaron rápido y son exactamente como se ven en las fotos.",
    "Buen producto, uso estas zapatillas para el gimnasio y son perfectas.",
    "Estas zapatillas tienen un diseño que combina con todo, muy contentos con la compra.",
    "Muy satisfecho con estas zapatillas, el precio es justo por la calidad que ofrecen.",
    "Me gustan mucho estas zapatillas, son cómodas y tienen buen agarre en diferentes superficies.",
  ],
  accesorio: [
    "Excelente accesorio, la calidad es muy buena y el diseño único.",
    "Este accesorio es perfecto, funcional y con un estilo moderno.",
    "Muy buen accesorio, versátil y con buenos acabados.",
    "La calidad del accesorio es notable, se nota que está bien fabricado.",
    "Gran compra, el accesorio es exactamente lo que buscaba.",
    "El accesorio llegó bien empacado y es mejor de lo que esperaba.",
    "Buen producto, uso este accesorio a diario y estoy muy satisfecho.",
    "Este accesorio tiene un diseño que llama la atención, recibo muchos cumplidos.",
    "Muy contento con este accesorio, la relación calidad-precio es excelente.",
    "Me gusta mucho este accesorio, es práctico y tiene un diseño atemporal.",
  ],
  mochila: [
    "Excelente mochila, espaciosa y con compartimentos bien distribuidos.",
    "Esta mochila es perfecta para el trabajo, cabe mi laptop y todos mis accesorios.",
    "Muy buena mochila, resistente y con un diseño moderno.",
    "La calidad de la mochila es superior, los cierres y costuras son muy resistentes.",
    "Gran compra, la mochila es cómoda de llevar incluso cuando está llena.",
    "La mochila llegó antes de lo esperado y es exactamente como se ve en las fotos.",
    "Buen producto, uso esta mochila para viajes cortos y es muy práctica.",
    "Esta mochila tiene un diseño que me encanta, funcional pero con estilo.",
    "Muy satisfecho con esta mochila, el precio es justo por la calidad que ofrece.",
    "Me gusta mucho esta mochila, es resistente al agua y tiene buenos bolsillos.",
  ],
  camiseta: [
    "Excelente camiseta, la tela es suave y la talla perfecta.",
    "Esta camiseta es muy cómoda, la uso tanto para hacer deporte como para el día a día.",
    "Muy buena camiseta, el diseño es genial y la calidad notable.",
    "La calidad de la camiseta es superior, después de varios lavados mantiene su forma y color.",
    "Gran compra, la camiseta es versátil y combina con todo.",
    "La camiseta llegó rápido y es exactamente como se ve en las fotos.",
    "Buen producto, tengo varias camisetas de esta marca y todas son excelentes.",
    "Esta camiseta tiene un ajuste perfecto, ni muy ajustada ni muy holgada.",
    "Muy contento con esta camiseta, la relación calidad-precio es excelente.",
    "Me gusta mucho esta camiseta, el material es fresco y perfecto para el verano.",
  ],
  sudadera: [
    "Excelente sudadera, abrigadora pero no demasiado pesada.",
    "Esta sudadera es perfecta para el clima fresco, cómoda y con buen estilo.",
    "Muy buena sudadera, la capucha tiene buen tamaño y los bolsillos son amplios.",
    "La calidad de la sudadera es notable, la tela interior es suave y cálida.",
    "Gran compra, la sudadera es versátil y se puede usar en diferentes ocasiones.",
    "La sudadera llegó bien empacada y es mejor de lo que esperaba.",
    "Buen producto, uso esta sudadera para salir a correr en las mañanas frías.",
    "Esta sudadera tiene un diseño simple pero elegante, muy contento con la compra.",
    "Muy satisfecho con esta sudadera, el precio es justo por la calidad que ofrece.",
    "Me gusta mucho esta sudadera, es cómoda y tiene un ajuste perfecto.",
  ],
  short: [
    "Excelente short, cómodo y con buen ajuste.",
    "Este short es perfecto para hacer deporte, ligero y transpirable.",
    "Muy buen short, la tela es de calidad y los bolsillos son funcionales.",
    "La calidad del short es superior, después de varios lavados sigue como nuevo.",
    "Gran compra, el short es versátil y se puede usar para diferentes actividades.",
    "El short llegó rápido y es exactamente como se ve en las fotos.",
    "Buen producto, uso este short para correr y es muy cómodo.",
    "Este short tiene un diseño que me gusta mucho, deportivo pero con estilo.",
    "Muy contento con este short, la relación calidad-precio es excelente.",
    "Me gusta mucho este short, el material seca rápido y es perfecto para el verano.",
  ],
}

// Función para obtener un comentario aleatorio para un post
export function getRandomBlogComment(): string {
  const randomIndex = Math.floor(Math.random() * BLOG_COMMENTS.length)
  return BLOG_COMMENTS[randomIndex]
}

// Función para obtener una reseña aleatoria para un post
export function getRandomBlogRating(): string {
  const randomIndex = Math.floor(Math.random() * BLOG_RATINGS.length)
  return BLOG_RATINGS[randomIndex]
}

// Función para obtener una reseña aleatoria para un producto según el tipo y género
export function getRandomProductReview(productType: string, gender: "male" | "female"): string {
  // Si el tipo de producto no existe, usar "accesorio" como fallback
  const type = productType in PRODUCT_REVIEWS_FEMALE ? productType : "accesorio"

  // Seleccionar la lista de reseñas según el género
  const reviewsList = gender === "female" ? PRODUCT_REVIEWS_FEMALE[type] : PRODUCT_REVIEWS_MALE[type]

  // Obtener una reseña aleatoria
  const randomIndex = Math.floor(Math.random() * reviewsList.length)
  return reviewsList[randomIndex]
}
